site_name: "Stone Bridge Computer Science Honor Society"
site_author: SBHS CS Honor Society
site_description: "Website for SBHS' CS Honor Society."

# github repository information
repo_name: SBCSHS/sbcshs-website
repo_url: https://github.com/SBCSHS/sbcshs-website
edit_uri: ""

# new colors
extra_css:
  - stylesheets/extra.css

# table of contents directories
#nav:
#  - Home: 'index.md'
#  - Docs: 'docs.md'
#  - GitHub: 'github.md'
#  - Design: 'design.md'

# theme
theme:
  name: material
  features:
    - content.tooltips
    - search.highlight
    - search.suggest
    - search.share
    - content.tabs.link 
    - content.code.annotate
#   - navigation.tabs
    - navigation.expand
    - navigation.tracking
    - navigation.instant
    - navigation.sections
#   - navigation.indexes
    - toc.integrate
  icon:
    logo: material/dog
    repo: fontawesome/brands/github
    edit: material/pencil
 # custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to system preference
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# material extensions
extra:
#  analytics:
#   provider: google
#   property: G-96JMH9MJRG
#   feedback:
#     title: Was this page helpful?
#     ratings:
#       - icon: material/emoticon-happy-outline
#         name: This page was helpful
#         data: 1
#         note: >-
#          Thanks for your feedback!
#       - icon: material/emoticon-sad-outline
#          name: This page could be improved
#         data: 0
#         note: >- 
#          Thanks for your feedback! Help us improve this page by
#          using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  generator: false
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/SBCSHS/sbcshs-website
      name: sbcshs-website
# consent:
#   title: Cookie consent
#   description: >-
#    We use cookies to recognize your repeated visits and preferences, as well
#    as to measure the effectiveness of our documentation and whether users
#    find what they're searching for. With your consent, you're helping us to
#    make our documentation better.

# plugins
plugins:
  - git-revision-date-localized: # date and time of edit
      enable_creation_date: true
      type: iso_datetime
      fallback_to_build_date: true
# - social: # social cards
#     cards: true
#     cards_dir: docs/images/social
  - glightbox: # image linking
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: "100%"
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
  - search

# markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex: # allows developers to display math equations with proper formatting
      generic: true
  - pymdownx.caret: # adds text formatting options involving ^
      smart_insert: true
      insert: true
      superscript: true
  - pymdownx.emoji: # emojis
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight: # adds code highlighting
      anchor_linenums: true
      use_pygments: true
      auto_title: true
      linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite # code highlight extensions
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.snippets: # allows snippets of code to be inserted into the website
      check_paths: true
      base_path:
        - "."
  - pymdownx.superfences: # allows code to be formatted properly and various other things.
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables
  - toc: # table of contents
      permalink: true

# javascript extension supplements
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js