# @format

site_name: "Stone Bridge Computer Science Honor Society"
site_author: "SBHS CS Honor Society"
site_description: "Website for the SBHS CS Honor Society."
site_url: https://sbcshs.github.io/sbcshs-website/

# github repository information
repo_name: "SBCSHS/sbcshs-website"
repo_url: "https://github.com/SBCSHS/sbcshs-website"
edit_uri: ""

# new colors
extra_css:
  - stylesheets/extra.css

# theme
theme:
  name: material
  features:
    - content.tooltips
    - search.highlight
    - search.suggest
    - search.share
    - content.tabs.link
    - content.code.annotate
    - navigation.tabs
    - navigation.footer
    - navigation.prune
    - navigation.expand
    - navigation.tracking
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - toc.integrate
  logo: "../assets/images/sbhs_450x450.png"
  custom_dir: overrides

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    #custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to system preference
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# material extensions
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SBCSHS/sbcshs-website
      name: sbcshs-website
# plugins
plugins:
  - git-revision-date-localized: # date and time of edit
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: false
  - glightbox: # image linking
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: "100%"
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
  - search

# markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex: # allows developers to display math equations with proper formatting
      generic: true
  - pymdownx.caret: # adds text formatting options involving ^
      smart_insert: true
      insert: true
      superscript: true
  - pymdownx.emoji: # emojis
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight: # adds code highlighting
      anchor_linenums: true
      use_pygments: true
      auto_title: true
      linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite # code highlight extensions
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.snippets: # allows snippets of code to be inserted into the website
      check_paths: true
      base_path:
        - "/"
  - pymdownx.superfences: # allows code to be formatted properly and various other things.
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - tables
  - toc: # table of contents
      permalink: true

# javascript extensions
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

nav:
  - Home: index.md
  - Recent Events: events.md
  - Information: information.md
  - Resources: resources.md
